:doctype: book
:toc: macro
:toclevels: 5
:source-highlighter: highlight.js
:icons: font
:pdf-theme: Unternehmenskonzept_Neu_gesamt.yml
:imagesdir: images
:pdf-page-size: a4
:toc-title: I. Inhaltsverzeichnis
:lang: DE
:hyphens:
:author: Sebastian Andreas Stiller
:docdate: {docdate}
:title: SPMG-Unternehmensgründungskonzept
:title-logo-image: image:logo.svg[pdfwidth=100, align=center]
:sectnums:
:sectnumlevels: 0
:title-page:
:chapter-label:

= Unternehmenskonzept Stiller und Partner Mediengruppe GmbH/Holding (SPMG)
{author} +
In der Fassung vom {docdate}

toc::[levels=3]

== II. Vorwort
Die Stiller und Partner Mediengruppe GmbH/Holding (SPMG) ist ein innovatives Medien und Unterhaltungsunternehmen, das sich auf die Entwicklung und Produktion von hochwertigen Multi-Medialen Inhalten spezialisiert hat. In diesem Dokument werden die genauen Pläne und Ziele zur Gründung der SPMG dargelegt. Hier wird die Geschichte hinter der Idee, die Visionen, der Aufbau und unser Auftrag als Dienstleister und Arbeitgeber beschrieben. Es werden die Produkte und Projekte vorgestellt, welche unser Kerngeschäft bilden, sowie die Werte, welche wir als Unternehmen vertreten. Zudem werden die Ziele und Strategien erläutert, welche wir verfolgen, um unsere Vision zu verwirklichen. Dieses Dokument dient als Leitfaden für die Gründung und Entwicklung der SPMG und soll potenziellen Investoren, Partnern und Mitarbeitern einen umfassenden Einblick in unser Unternehmen geben.

=== II.1 Haftung und Geheimhaltung
Die Informationen in diesem Dokument sind vertraulich und dürfen nicht ohne ausdrückliche schriftliche Genehmigung der Stiller und Partner Mediengruppe GmbH/Holding (SPMG), vertreten durch den Gründer und Chief Creative Officer (CCO) **Sebastian Andreas Stiller**, an Dritte weitergegeben oder veröffentlicht werden. 

=== II.2 Urheberrecht und geistiges Eigentum

**Alle Inhalte**, einschließlich, aber nicht beschränkt auf **Texte**, **Grafiken**, **Bilder**, **Logos**, **Marken**, **Designs**, **Software** und andere Materialien in diesem Dokument oder anderen Veröffentlichungen sind Eigentum der SPMG, vertreten durch den Gründer und CCO **Sebastian Andreas Stiller**, und sind durch Urheberrechtsgesetze und andere geistige Eigentumsrechte geschützt. 

Die SPMG, vertreten durch den Gründer und CCO **Sebastian Andreas Stiller**, behält sich alle Rechte vor, die nicht ausdrücklich in diesem Dokument gewährt werden. Jede unautorisierte Nutzung, Vervielfältigung, Verbreitung oder Veröffentlichung von Inhalten aus diesem Dokument oder anderen Veröffentlichungen der SPMG, vertreten durch den Gründer und CCO **Sebastian Andreas Stiller**, ist strengstens untersagt und kann rechtliche Konsequenzen nach sich ziehen.

=== II.3 Marken und Logos
SPMG und das SPMG-Logo sind eingetragene Marken der Stiller und Partner Mediengruppe GmbH/Holding (SPMG), vertreten durch den Gründer und CCO **Sebastian Andreas Stiller**. Alle anderen in diesem Dokument oder anderen Veröffentlichungen der SPMG, vertreten durch den Gründer und CCO **Sebastian Andreas Stiller**, erwähnten Markennamen, Produktnamen, Dienstleistungsmarken oder Firmennamen sind Eigentum ihrer jeweiligen Inhaber.

=== II.4 Haftungsausschluss
Die Informationen in diesem Dokument werden "wie besehen" bereitgestellt, ohne jegliche ausdrückliche oder stillschweigende Gewährleistung. Die SPMG, vertreten durch den Gründer und CCO **Sebastian Andreas Stiller**, übernimmt keine Verantwortung für die Genauigkeit, Vollständigkeit oder Aktualität der Informationen in diesem Dokument oder anderen archivierten Veröffentlichungen. Jegliche Nutzung der Informationen in diesem Dokument ab Veröffentlichung erfolgt auf eigenes Risiko.

== III. Kontakt 
Für weitere Informationen oder Anfragen bezüglich der Stiller und Partner Mediengruppe GmbH/Holding (SPMG) können Sie uns unter den folgenden Kontaktdaten erreichen:

Ansprechpartner: **Sebastian Andreas Stiller** (Gründer und Chief Creative Officer - CCO)

* **Adresse**: To be Announced
* **Telefon**: +43 660 2084555
* **E-Mail**: mailto:kontakt@sebastianstiller.at[kontakt@sebastianstiller.at]


include::chapters/1_Intro_History.adoc[]

include::chapters/2_Company_philosophy.adoc[]

include::chapters/3_Executive_Summery.adoc[]

include::chapters/4_Compliance_HR_Finance.adoc[]

include::chapters/5_Products_Projects.adoc[]

include::chapters/6_GuestServices_Hospitality.adoc[]

include::chapters/7_Operations_Security.adoc[]

include::chapters/8_Operations_Medical.adoc[]

include::chapters/9_Fire_Branch.adoc[]

include::chapters/10_Logistics.adoc[]

include::chapters/11_Vehicle_fleetmanagement.adoc[]

include::chapters/12_Vehicles_fleet.adoc[]

include::chapters/13_ERPDS_System.adoc[]

include::chapters/14_ERPDS_System_MobileApp.adoc[]

include::chapters/15_requirements.adoc[]

include::chapters/16_Paysystem.adoc[]

include::chapters/17_Uniform_corporate_identity.adoc[]

include::chapters/Company_agreement.adoc[]

