= 12 Fahrzeuge und Unternehmensflotte 

In diesem Kapitel wird die Zusammensetzung der Gesamten Unternehmensflotte der *Stiller und Partner Mediengruppe* und aller ihrer Abteilungen näher erläutert. 

== 12.1 Flottenweit normierte Standards 

Im Folgenden Abschnitt werden zunächst die für Alle Fahrzeuge im Dienst der *SPMG* genauer behandelt.

=== 12.1.1 Isolation der Fahrzeuginfrastruktur (Härtung)

**Vollständige Backend-Deaktivierung:**:: Für alle Neufahrzeuge werden die herstellerseitigen Online-Dienste (VW Connect / We Connect Plus) sowie kommerzielle Datenpakete direkt im Werks-Backend der Volkswagen AG dauerhaft gesperrt.

**Daten-Isolierung (eCall-Ausnahme):**:: Die im Fahrzeug integrierte eSIM-Karte wird für jeglichen regulären Datenverkehr blockiert. 

[WARNING]
====
 Die gesetzlich vorgeschriebene Notruffunktion (EU-eCall 112) bleibt im Crash-Fall direkt zur öffentlichen Rettungsleitstelle voll funktionsfähig.
====

**Lokaler Betriebsmodus:**::
Das Bordeigene Infotainment-System (über Android Auto) wird in einen Abgesicherten Modus geschaltet bei dem keinerlei Daten an Hersteller- oder Unternehmensfremde Firmen gesendet werden. Die Sprachbefehle werden bis auf jene die Direkt mit dem Mobile Device des Fahrers ("Rufe 'X' an","Sende Nachricht an 'X'" ) deaktiviert. Weiters werden sämtliche Herstelller- und Unternehmnesfremden KI-Dienste (darunter ChatGPT von OpenAI, Claude von Anthropic oder auch Gemini von Google) deaktiviert und wenn möglich deinstalliert. 

**Pannentaste:**:: Die fahrzeugeigene Pannentaste im Dachhimmel und die damit verbundenen VW-Connect Dienste werden im Zuge des Behördenumbaus elektrisch stillgelegt bzw. blindgeschaltet. Technische Defekte werden ausschließlich über die betriebseigene Kommunikationsstruktur und Navigation wird über ein Seperates Navigationsgerät (auf dem auch Aufträge oder Einsätze gespiegelt werden) abgewickelt.

=== 12.1.2 Flottenweiter Mittelaufbau
Jedes Fahrzeug wird mit einer eigens angepassten KFG-Konformen Mittelkonsole ausgestattet. 

**Sonderanlagen-Bedienteil**:: Das Steuerelement für die gesamte Sonderlicht- bzw. Sondersignalanlage wird bei allen Fahrzeugen an der oberen Mittelfläche des Amaturenbrettes angebracht. Dieses steuert: +
* Warnlicht- bzw. bei zugelassenen Einsatzfahrzeugen entsprechend dem §20 abs. 4 KFG Sondersignalanlage (Blaulicht und Folgetonhorn)
* Umfeldbeleuchtung (Scene-Lights): Arbeitsscheinwerfer welche jeweils in alle Richtungen (Vorne, Hinten, Links und Rechts) in Dual-Ausführung. 
* Matrixanzeigen und Early Warner-Anlagen 
* Sonderfunktion "Heli-Mode" * 
* IR-Lichtmodul

[NOTE]
====
die mit * markierten Punkte werden gesondert im entsprechenden Abschnitt erklärt.
====

**Funk und Docking**::
in der eigentlichen Mittelkonsole zwischen Fahrer und Beifahrer befinden sich die Geräte für den Betriebsinternen Tetra-Funk sowie das entsprechende Handmikrofon/Faustmikrofon. Des weitere befindet sich eine crash-sichere, ebenfalls KFG Konforme Dockingstation für das Panasonic Toughbook des Fahrers. Dieses fungiert im Fahrzeug sowohl als Mobile Office (bei abgeschaltetem Motor) und als Einsatzleitsystem über das Webbasierte ERPDS-System.

**Dokumenten und Materialfach**:: 
Im hinteren Bereich (auf höhe der Rückenlehnen) befindet sich Stauraum für das Fahrzeugbuch (die Fahrzeugmappe) sowie ein Spender (Halterung) für Einweg Nitril Handschuhe

=== 12.1.3 Gehärteter KFZ-Router

Jedes Fahrzeug ist ebenfalls mit einem eigenen KFZ-Router (Automotive Router) ausgestattet welcher einen konstanten VPN Tunnel zum Zentralserver herstellt. Hierdurch wird garantiert, dass die Fahrzeuge auch außerhalb der Netzreichweite der Liegenschaften immer eine Anbindung an die Internen Systeme behalten. 

=== 12.1.4 Toughbook-Anbindung

Die Verbindung des Einsatzleitsystems erfolgt aus Gründen des Ausfallschutzes und Sicherheitsbedenken (jamming- /Hacking-Schutzes) strikt Kabelgebunden mittels geschirmter LAN-Kabel (*CAT 6e*) und galvanisch getrennten Stromkabel welche mit dem Zweitbatteriesystem verbunden ist. 

=== 12.1.5 Zweitbatteriesystem und Rettbox

Jedes Fahrzeug wird mit einer Lade- oder Zweitbatterie ausgestattet. Weiters werden alle Fahrzeuge mit einem Außenladesystem "RettBox" der Firma Marechal Electric ausgestattet. Dieses ermöglicht die Fahrzeuge in den Garagen und an Liegenschaften über ein entsprechendes Kabel zu Laden und hat den Vorteil das bei aktivierung der Zündung dieses Kabel beschädigungsfrei abgesprengt (abgekoppelt) wird.

=== 12.1.6 Navigationsystem "LardisOne
Die gesamte Navigation im Fahrzeug wird über ein dediziertes LardisOne Gerät abgewickelt. +
Hierbei arbeitet dieses Gerät ausschließlich im Navigationsmodus (keine Anzeige von zusätzlichen Informationen wie Funkgruppen oder ähnliches). 

=== 12.1.7 Einsatz-/Auftragsdaten-Empfang
Die Aufträge bzw. Einsätze werden grundlegend über das Unternehmensintere **ERPDS-System** disponiert und empfangen an das im Fahrzeug befindliche Toughbook und im Pager-Prinzip an die Mobile Devices der Mitarbeiter gesendet und über das Fahrzeug-Netzwerk an das Navigationsgerät (Berufungsort und Zielort) geleitet.

=== 12.1.8 Tetrafunk im Fahrzeug
Jedes Fahrzeug ist mit einem Sepura Fahrzeug-Funkgerät ausgestattet. dieses ermöglicht auch während dem Fahrbetrieb die reibungslose Kommunikation mit der Unternehmenseigenen Leitzentrale und den anderen Unternehmensmitarbeitern. 

=== 12.1.9 Funkkennungsbeschilderung
Jedes Fahrzeug ist mit einer eindeutigen Tetra-Funkkennung ausgestattet. Diese ist sowohl am Fahrzeugfunkgerät ersichtlich und auch von Außen in der Windschutzscheibe erkennbar. Hiebei wird ein gut lesbares, KFG/STVO konformes Schild an der Innenseite angebrachte Plakette in Corporate Design mit der Funkkennung in Retroreflektierender Farbe (Silber/Weiß)

== 12.2 Flottenmodelle 
In diesem Abschnitt werden die Grundlegenden Hersteller und Modelle der Flottenfahrzeuge aufgelistet. 

[cols="3", options="header"]
.Fahrzeugübersicht-Boden
|===
| Hersteller | Modell | Zwecke 
| VW | Amarok | Einsatzleitwagen
|VW| T 6.1| Streifenwagen, Halbgruppenfahrzeug, Technischer Dienst
| VW | Passat | Streifenwagen, Ermittlungsdienst, Personenschutzfahrzeug
| Mercedes | Sprinter | RTW, Kühltransporter, Unfallaufnahmedienst, Arrestantentransport
| Mercedes | A6 Limosine |  VIP-Transport
| Mercedes | A6 Limosine Stretch| VIP/Event-Transport
| Mercedes| G-Klasse| Interventionsdienst (EL)
| MAN | TGL 7.X| Mittlere Logistik
| MAN | TGX 18.X| Schweres Logistikfahrzeug , ELW 2 Zugmaschine
| MAN| Lion´s Coach | Akademie Transportdienst
|===

[cols="3", options="header"]
.Fahrzeugübersicht-Luft
|===
| Hersteller | Modell | Zwecke 
| Airbus Helicopters | H-145 | Sicherheitsdienst (Streifen und Luftüberwachung), Rettungsdienst (Luftrettung)
|Airbus Helicopters| H-225 | Interventionsdienst, Mittlere Logistik
|===