= SPMG - Gesellschaftsvertrag 
In der Fassung vom {docdate}

== Präambel
Im folgenden Dokument/Abschnitt wird der Gesellschaftsvertrag der Stiller und Partner Mediengruppe GmbH/Holding (im weiteren Verlauf als "*SPMG*")
beschrieben. 

Dieser Vertrag regelt eindeutig die Rechte, Pflichten, Verantwortlichkeiten und Zuständigkeiten der einzelnen Gesellschafter, die Anteile an der SPMG halten, die Geschäftsführung, die Gewinnverteilung, die Finanzierung, die Entscheidungsprozesse, die Entscheidungsgewalten(-gewichtungen) und die Auflösung der Gesellschaft. 

== Gesellschafter und Funktionen

=== Chief Creative Officer (CCO)
Der Chief Creative Officer (CCO) ist der *Gesamtverantwortliche* für die *kreative Ausrichtung* und die *künstlerischen Geschäftsprozesse und Gewinnerwirtschaftung* der *SPMG*. +

CCO der SPMG:: 
 Sebastian Andreas Stiller +
 geboren am 20.09.2001 +
 in Wien, Österreich

=== Chief Financial Officer (CFO)
Der Chief Financial Officer (CFO) ist der *Gesamtverantwortliche* für die *finanzielle Ausrichtung* und die *finanziellen Geschäftsprozesse und Gewinnerwirtschaftung* der *SPMG*. +

CFO der SPMG:: 
 TBD

=== Chief Security Officer (CSO)
Der Chief Security Officer (CSO) ist der *Gesamtverantwortliche* für die *sicherheitsrelevante Ausrichtung* und die *sicherheitsrelevanten Geschäftsprozesse und Behördliche Aufgaben* der *SPMG*. +

CSO der SPMG:: 
 TBD

=== Chief Medical Officer (CMO)
Der Chief Medical Officer (CMO) ist der *Gesamtverantwortliche* für das *medizinische Wohlbefinden* der Mitarbeiter und Gäste in allen Anlagen der *SPMG*. +

CMO der SPMG:: 
 TBD

=== Chief Technology Officer (CTO)
Der Chief Technology Officer (CTO) ist der *Gesamtverantwortliche* für die *technologische Infrastruktur* deren Weiterentwicklung und Instandhaltung innerhalb der Anlagen der *SPMG*. +

CTO der SPMG::
    TBD

=== Chief Production Officer (CPO)
Der Chief Production Officer (CPO) ist der *Gesamtverantwortliche* für die *Medienproduktionen* und deren *Gewinnerwirtschaftung* innerhalb der *SPMG*. +

CPO der SPMG::
    TBD

Die Oben genannten Personen sind für Ihre jeweiligen Verantwortungsbereiche zuständig und tragen die volle Verantwortung für die Erfüllung ihrer Aufgaben und Pflichten gemäß diesem Gesellschaftsvertrag. Alle Entscheidungen, die in ihren Verantwortungsbereichen getroffen werden, müssen im Einklang mit den Zielen und Werten der SPMG stehen und zum Wohle des Unternehmens und seiner Gesellschafter beitragen.

Die Entscheidungen dürfen jedoch nie einen Nachteil für die Kunden der SPMG oder die Öffentliche Wahrnehmung der SPMG darstellen. Alle Entscheidungen müssen stets im Einklang mit den Interessen der Kunden und der öffentlichen Wahrnehmung der SPMG stehen, um das Vertrauen und die Zufriedenheit unserer Kunden zu gewährleisten und die Reputation unseres Unternehmens zu schützen.


