= Operations & Security
In diesem Kapitel werden die operativen Abläufe und Sicherheitsmaßnahmen des Unternehmens beschrieben. Es umfasst die täglichen Geschäftsprozesse, die IT-Infrastruktur, sowie die Strategien zur Gewährleistung der Datensicherheit und des Schutzes vor Cyberbedrohungen.

Im weiteren werden die Mitarbeiter des Sicherheits- und Operationsteam als "Beamte/n" bezeichnet. Diese Bezeichnung soll weder Polizeiliche noch Hoheitliche Aufgaben suggestieren, sondern dient lediglich der internen Unterscheidung und Organisation innerhalb des Unternehmens. Alle Mitarbeiter, die in diesem Kapitel beschrieben werden, sind Angestellte der Stiller und Partner Mediengruppe GmbH/Holding (SPMG) und unterliegen den entsprechenden arbeitsrechtlichen Bestimmungen.

Im weiteren werden die Mitarbeiter der Landespolizei als "Polizist/in" oder "Exikutivbedienstete/r" bezeichnet. Diese Bezeichnungen dienen der Klarheit und Unterscheidung zwischen den internen Sicherheitskräften des Unternehmens und den externen Strafverfolgungsbehörden. Alle Erwähnungen von "Polizist/in" oder "Exikutivbedienstete/r" beziehen sich auf die Mitarbeiter der  zuständigen Landespolizeidirektion (Wien/NÖ), die für die Aufrechterhaltung der öffentlichen Sicherheit und Ordnung verantwortlich sind.

Im weiteren wird die Bezeichnung "Exekutive" für die Polizei im gesamten verwendet. Hierbei wird rein nur die Polizei gemeint und nicht die anderen Mitglieder der Exekutive, wie z.B. die Landesregierung, die Bundesregierung oder andere Behörden. Alle Erwähnungen von "Exekutive" beziehen sich ausschließlich auf die Polizei und deren Mitarbeiter, die für die Aufrechterhaltung der öffentlichen Sicherheit und Ordnung verantwortlich sind. 


== Sicherheitsstrategie
Die Sicherheitsstrategie des Unternehmens basiert auf einem mehrschichtigen Ansatz, der sowohl physische als auch digitale Sicherheitsmaßnahmen umfasst.


== Operations Security

=== Unternehmenseigener Sicherheitsdienst
Die SPMG setzt bei der Sicherung ihrer Betriebsstätten und Veranstaltungen auf einen undernehmenseigenen Sicherheitsdienst, welcher mit speziell geschulten und Taktisch ausgebildeten Beamten besetzt ist. Dieser Sicherheitsdienst ist für die Überwachung der Zugänge, die Durchführung von Sicherheitskontrollen und die Reaktion auf Sicherheitsvorfällen in allen Anlagen der SPMG verantwortlich. 

Die Taktische Ausbildung und Bewaffnung der Sicherheitsbeamten resultiert aus der Notwendigkeit, auf potenzielle Bedrohungen von Mitarbeitern, Kunden, Gästen oder VIP Personen angemessen reagieren zu können. Diese Maßnahmen dienen dem Schutz aller Personen auf den Geländen und Betriebstätten der SPMG und sollen vor allem die Exekutive zu entlasten. 

Die Zusammenarbeit mit der Exekutive erfolgt hierbei sowohl bei Sicherheitsangelegenheiten, im Rahmen von Ermittlungen, aus auch bei der Plannung und Durchführung von diversen Projekten, Veranstaltungen und Produktionen( siehe Abschnitt Produkte und Projekte).

=== Einheiten des Sicherheitsdienstes 
Der Sicherheitsdienst der SPMG ist in verschiedene Einheiten unterteilt, um eine effektive und spezialisierte Sicherheitsversorgung zu gewährleisten. Dazu gehören:


[plantuml, org-chart-security, svg]
----
@startuml
skinparam packageStyle rectangle
allowmixing

skinparam rectangle<<text>> {
    BackgroundColor transparent
    BorderColor transparent
    Shadowing false
}

title Organigramm - Abteilungsstruktur - Sicherheitsdienst

package "Security Operations" as SO {
    rectangle "CSO" as CSO
    
    object "Security and Patrol Unit" as SPU
    object "Special Intervention Unit" as SIU
    object "VIP Close Protection Unit" as VCPU
    object "Event Security Unit" as ESU
    object "Arial Support Unit" as ASU {
        Flightchief: TBD
        Groundchief: TBD
    }
    object "Investigation and Intelligence Unit" as IIU
    object "K9 Unit" as K9
    object "Security Logistics Unit" as SLU
    object "SLU-Werttransport" as SLU_WT
    object "SLU-Arrestantentransport" as SLU_AT
    object "SLU-VIP Shuttle Service" as SLU_VIP
    object "SLU-VIP Medical Service" as SLU_VIP_Med

    CSO -down-> SPU
    CSO -down-> SIU
    CSO -down-> VCPU
    CSO -down-> ESU
    CSO -down-> ASU
    CSO -down-> IIU
    CSO -down-> K9
    CSO -down-> SLU
    
    SLU -down-> SLU_WT
    SLU -down-> SLU_AT
    SLU -down-> SLU_VIP
    SLU_VIP -down-> SLU_VIP_Med
} 
@enduml
----

* **Security and Patrol Unit (SPMG-SPU)**: +
Dies sind die Boots on the Ground. Sie sind für die Überwachung der Betriebsstätten, die Durchführung von Sicherheitskontrollen und die Reaktion auf Sicherheitsvorfälle verantwortlich. Sie patrouillieren regelmäßig die Anlagen der SPMG, um potenzielle Bedrohungen zu erkennen und zu verhindern.

* ** Special Intervention Unit (SPMG-SIU)**: +
Diese Einheit dient als Interventionsasset für Hochrisikolagen und Schwere Sicherheitsvorfälle zuständig und entsprechend ausgerüstet und geschult. Sie arbeitet am Engsten mit der Exekutive zusammen, um bei Bedarf die Einheiten der Exekutive zu ergänzen und zu unterstützen.

* **VIP Close Protection Unit (SPMG-VCPU)**: +
Diese Einheit ist für den Schutz von VIP Personen(Prominente, Politiker, Ehrengäste) zuständig, welche sich auf den Geländen der SPMG aufhalten. Sie sind speziell geschult, um potenzielle Bedrohungen zu erkennen und zu neutralisieren, um die Sicherheit der VIP Personen zu gewährleisten. Hiebei wird auch wieder eng mit den Personenschützern der Exekutive (stichwort: Politiker und Ehrengäste) zusammengearbeitet, da diese die grundsätzliche Zuständigkeit haben.  

* **Event Security Unit (SPMG-ESU)**: +
Diese Einheit ist für die Planung und Ergänzenden Durchführung von Sicherheitsmaßnahmen bei Großveranstaltungen, wie z.B. Konzerten, Festivals oder Firmenfeiern, zuständig. Sie arbeitet eng mit der Exekutive zusammen, um die Sicherheit der Veranstaltungsteilnehmer zu gewährleisten und potenzielle Bedrohungen zu erkennen und zu verhindern.

* **Arial Support Unit (SPMG-ASU)**: +
Diese Einheit ist für den Betrieb, die Wartung und die generelle Einsatzplanung der Drehflügler als Unterstützungseinheiten der SPMG. Sie stellen also die Hubschrauber für die Sicherheitsoperationen der SPMG bereit, welche sowohl für die Überwachung der Betriebsstätten, die Unterstützung bei Sicherheitsvorfällen.

* **Investigation and Intelligence Unit (SPMG-IIU)**: +
Diese Einheit ist das Rückgrat der Sicherheitsstrategie der SPMG. Sie ist für die Durchführung von Erhebungen im Rahmen von Background Checks, Asset Protection(Ladendetektive), Sicherheits- und Risikoanalysen. Sie ist auch für die ersten Ermittlungen bei Gefährdungslagen von Mitarbeitern und VIPs zuständig. Sie ist auch im ständigen Austausch mit der Exekutive, um Informationen über potenzielle Bedrohungen zu teilen und gemeinsam Strategien zur Gefahrenabwehr zu entwickeln.

* **K9 Unit (SPMG-K9)**: +
Diese Einheit ist für den Einsatz von speziell ausgebildeten Hunden zuständig, welche bei der Überwachung der Betriebsstätten, der Durchführung von Sicherheitskontrollen und der Vorbeugenden Maßnahmen bei Großveranstaltungen eingesetzt werden. Hierbei gibt es verschiedene Spezialisierungen, wie z.B. Sprengstoffspürhunde, Drogenspürhunde oder Personenspürhunde, welche je nach Bedarf eingesetzt werden.

* **Security Logistics Unit(SPMG-SLU)**: +
Die Security Logistics Unit der SPMG ist eine Sondereinheit, welche für Hochrisiko-Transporte im Auftrag der SPMG in den Anlagen und auch außerhalb. 
Diese Transporte umfassen vor allem: +

** *Werttransporte*: +
Jede Tageslosung die in den Anlagen der SPMG erwirtschaftet wird, wird von der Security Logistics Unit abgeholt und in unserem Security Center gezählt und anschließend unter höchsten Sicherheitvorkehrungen zu einer Partnerbank gebracht. Dadurch wird garantiert das keinerlei einnahmen beim Transport zur Bank gestohlen werden können. 

** *Arrestantentransporte*: +
Jede Person welche nach der Verübung einer Strafbaren handlung wird von unserem Sicherheitsdienst entsprechend Angehalten und von der SLU in das Sicherheitszentrum zur Internen Vorfallsdokumentation verbracht.

** *VIP-Shuttle Service*: +
Im Rahmen unseres VIP-Shuttle Services werden können VIPs und geladene Ehrengäste durch unsere fähigen Einsatzfahrer der SLU zwischen Terminen und Ihrer Unterkunft transportiert werden. 

** *VIP-Medical-Shuttle Service*: +
Auf bedarf kann auch eine Abholung mit Medizinischer Begleitung (NFS-NKI oder bei besonderem Bedarf mit Arzt) durchgeführt werden. +
Dieses und das VIP-Shuttle-Service arbeiten auch sehr eng mit der Close Protection Unit (SPMG-VCPU) zusammen um die Bestmögliche Experience für den Gast zu garantieren.

== IT-Security
aber auch die beste physische Sicherheit kann nicht helfen, wenn die IT-Infrastruktur des Unternehmens nicht ausreichend geschützt ist. Daher legt die SPMG großen Wert auf die Implementierung von robusten IT-Sicherheitsmaßnahmen, um die Vertraulichkeit, Integrität und Verfügbarkeit der Daten und Systeme zu gewährleisten.
Die IT-Sicherheitsstrategie der SPMG umfasst die folgenden Einheiten: 

* **Network Security Unit (SPMG-NSU)**: +
Diese Einheit ist für die Sicherung der Netzwerkinfrastruktur des Unternehmens zuständig. Sie implementiert und überwacht Firewalls, Intrusion Detection Systems (IDS) und diversen anderen Sicherheitsmaßnahmen, um unautorisierte Zugriffe zu verhindern und potenziell katastrophale Sicherheitsvorfälle, Ausfälle oder Datenlecks zu verhindern. Sie sind auch für die regelmäßige Überprüfung und Aktualisierung der Sicherheitsrichtlinien und -protokolle und die durchführung von Schulungen im Bereich IT-Sicherheit für die Mitarbeiter zuständig. +
Sie arbeiten auch eng mit den Cybercrime Einheiten der Exekutive und der DSN (Direktion Staatsschutz und Nachrichtendienst) zusammen, um Informationen über potenzielle Bedrohungen zu teilen und gemeinsam Strategien zur Gefahrenabwehr zu entwickeln.

* **Network Service Engineering Unit (SPMG-NSEU)**: +
Diese Einheit ist für die Planung, Implementierung und Wartung der Netzwerkinfrastruktur des Unternehmens zuständig. Sie stellt sicher, dass die Netzwerkinfrastruktur den Anforderungen des Unternehmens entspricht und gleichzeitig sicher und zuverlässig ist. Sie arbeiten eng mit der Network Security Unit (SPMG-NSU) zusammen, um sicherzustellen, dass die Netzwerkinfrastruktur den Sicherheitsanforderungen entspricht und potenzielle Schwachstellen identifiziert und behoben werden.

== Medizinische Versorgung
Die SPMG legt auch großen Wert auf das Wohlbefinden ihrer Mitarbeiter und Gäste.
Daher beschäftigt die SPMG ein Team von medizinischem Fachpersonal, welches für die medizinische Versorgung und Notfallversorgung auf den Betriebsstätten und Veranstaltungen des Unternehmens zuständig ist. Dieses Team arbeitet eng mit den örtlichen Rettungsdiensten und Krankenhäusern zusammen, um sicherzustellen, dass im Falle eines medizinischen Notfalls schnell und effektiv reagiert werden kann. Sie sind auch für die Durchführung von Erste-Hilfe-Schulungen für die Mitarbeiter zuständig. 
Hiebei wird generell unterschieden zwischen der Arbeitsmedizinischen Versorgung, welche sich um die Gesundheit der Mitarbeiter kümmert, und der Notfallmedizinischen Versorgung, welche für die medizinische Versorgung bei Notfällen auf den Betriebsstätten und Veranstaltungen zuständig ist.


[plantuml, org-chart-medical, svg]
----
@startuml
skinparam packageStyle rectangle

' Dieser Befehl erlaubt das Mischen von verschiedenen Elementtypen (Object & Rectangle)
allowmixing

' Definition eines Styles für reinen Text
skinparam rectangle<<text>> {
    BackgroundColor transparent
    BorderColor transparent
    Shadowing false
}

title Organigramm - Abteilungsstruktur - Medizinische Versorgung

package "Medical Operations" as MO {
    rectangle "CMO" as CMO
    
    object "Arbeitsmedizin" as AM
    object "Sanitätsdienst" as SD
    object "Medizinisch Präventive Maßnahmen" as MPM
    object "Flugrettung" as HEMS{
        Flightchief: TBD
        Groundchief: TBD
}
    object "Rettungshunde" as R_K9

    CMO -down-> AM
    CMO -down-> SD
    AM -down-> MPM
    CMO -down-> HEMS
    CMO -down-> R_K9
} 

@enduml
----

* **Arbeitsmedizinische Versorgung**: +
Die Arbeitsmedizinische Versorgung wird von einem Team von Arbeitsmedizinern und Gesundheitsexperten bereitgestellt. Sie sind für die Durchführung von Gesundheitschecks, Tauglichkeitsuntersuchungen und die Entwicklung von Gesundheitsprogrammen für die Mitarbeiter zuständig. Sie arbeiten eng mit der Personalabteilung zusammen, um sicherzustellen, dass die Arbeitsbedingungen sicher und gesundheitsfördernd sind.
** **Medizinisch Präventive Maßnahmen**: +
Die Einheit für Medizinisch Präventive maßnahmen ist eine Untereinheit der Arbeitsmedizin und beschäftigt sich mit der Analyse von Gesundheitsdaten der Mitarbeitern und öffentlich Verfügbaren Daten um zu garantieren das der Ausbruch einer Krankheitwelle oder Pandemie früh erkannt wird und entsprechende Maßnahmen zum Schutz der Mitarbeiter und Gäste eingeleitet werden. 

* **Sanitätsdienstliche Betreuung**: +
Um auf alle Eventualitäten vorbereitet zu sein ist es nicht nur Wichtig einen Starken Sicherheitsdienst sondern auch eine gute Notfallversorgung und damit wir das in allen Anlagen und auf allen Events der SPMG gewährleisten können.
** **Bodengebundener Sanitätsdienst**: +
Der Bodengebundene Sanitätsdienst ist bei jedem Event, Dreharbeiten und in der Erlebniswelt um im Falle des Falles Personen Erstzuversorgen und dann einer höheren Medizinischen Versorgung (KH) zuzuführen.
** **Hubschraubergebundener Sanitätsdienst (HEMS)**: +
Um auch auf besondere Medizinische Notfälle vorbereitet zu sein betreibt die SPMG auch eine Flotte aus mehreren H145 Rettungshubschrauben um die bestmögliche Versorgung zu gewährleisten. 
** **Sanitäts-Rettungshunde**: +
Um auch bei Sonderlagen eine Bestmögliche Versorgung von Personen gewähleisten zu können beherbergt die SPMG neben ihren Diensthunden auch eine kleine Einheit von speziell für den Rettungsdienst ausgebildete Hunde.
 

