= Dienstbekleidung und Corporate Identity

In diesem Abschnitt werden die grundlegenden Regelungen im Bezug zur *Dienstbekleidung* und der *Corporate Identity (Logo und Farbschema)*

== Dienstbekleidung und Uniformen

Ein Unternehmen ist nur so seriös wie seine Mitarbeiter. Aus diesem Grund muss der Mitarbeiter auch so Seriös aussehen wie die Seriösität des Unternehmen es darstellen soll. Aus diesem Grund setzt auch die Stiller und Partner Mediengruppe GmbH/Holding (SPMG) auf eine Standartisierte Dienstbekleidung und Uniform 

[NOTE]

Es wird hier grundsätzlich zwischen der Dienstbekleidung und der Uniform unterschieden. Die Dienstbekleidung bezeichnet hier also die Kleidung welche Personen tragen müssen, welche in den Bereichen Unternehmensleitung, Management und Vertrieb tätig sind. Uniformen werden von Personen getragen, wenn sie also in Operativen Bereichen(Sicherheit, Sanitätswesen, Brandschutz, Produktion und Technik und Logistik) tätig sind 

=== Standard Dienstalltag 

 

==== Unternehmensleitung, Management und Vertrieb


=== Representationsanläße 



=== Besondere Dienste 

